# Generated by Django 4.2.4 on 2024-09-18 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total price of the payment.",
                        max_digits=100,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Time when the payment was created.",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("NEW", "NEW"),
                            ("PAYMENT_FAILURE", "PAYMENT_FAILURE"),
                            ("PAYMENT_SUCCESS", "PAYMENT_SUCCESS"),
                        ],
                        help_text="State of the payment.",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Associated order for the payment.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
