# Generated by Django 4.2.4 on 2024-09-18 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("shop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="account",
            field=models.ForeignKey(
                help_text="User account owning this cart item.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                help_text="Product associated with the cart item.",
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.product",
            ),
        ),
    ]
