# Generated by Django 4.2.4 on 2024-09-18 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the product category.", max_length=50
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description of the product category.",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image of the product.", upload_to="product_images"
                    ),
                ),
                (
                    "thumbnail",
                    models.BooleanField(
                        default=False,
                        help_text="Is this image the thumbnail for the product?",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Time when the image was created."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the product.", max_length=50),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Description of the product.", max_length=255
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Unit of measurement for the product (e.g., kg, piece).",
                        max_length=10,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Unit price of the product.",
                        max_digits=100,
                    ),
                ),
                (
                    "in_stock",
                    models.IntegerField(
                        help_text="Quantity of the product available in stock."
                    ),
                ),
                (
                    "sold",
                    models.IntegerField(default=0, help_text="Number of units sold."),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Time when the product was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Time when the product was last updated.",
                    ),
                ),
                (
                    "special_offer",
                    models.BooleanField(
                        default=False, help_text="Is the product on special offer?"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is the product active and visible?"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category to which the product belongs.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shop.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Products",
                "ordering": ("-created_at",),
            },
        ),
    ]
