# Generated by Django 4.2.4 on 2024-05-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_product_seller_alter_product_sold"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="thumbnail",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="product_images"),
        ),
    ]
