# Generated by Django 4.2.4 on 2023-09-14 15:30

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(default='xyz', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default='xyz', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+48 111 111 111', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default='xyz', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 15, 30, 24, 850278, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='special_offer',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media\\product_images'),
        ),
    ]
