# Generated by Django 4.2.4 on 2024-04-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="mode",
            field=models.TextField(
                choices=[("ADMIN", "ADMIN"), ("USER", "USER")], default="USER"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="status",
            field=models.TextField(
                choices=[
                    ("NEW", "NEW"),
                    ("ACTIVE", "ACTIVE"),
                    ("BLOCKED", "BLOCKED"),
                    ("BANNED", "BANNED"),
                    ("REMOVED", "REMOVED"),
                ],
                default="NEW",
            ),
        ),
    ]
