# Generated by Django 4.2.4 on 2024-09-18 13:33

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="First name of the address holder.", max_length=50
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Last name of the address holder.", max_length=50
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="Street name for the shipment.", max_length=50
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Phone number associated with the address.",
                        max_length=128,
                        region=None,
                    ),
                ),
                (
                    "city",
                    models.CharField(help_text="City for the shipment.", max_length=50),
                ),
                (
                    "postal_code",
                    models.CharField(
                        help_text="Postal code for the shipment.", max_length=6
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        help_text="State or province for the shipment.", max_length=50
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Country for the shipment.", max_length=50
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Time when the address was created.",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("NEW", "NEW"),
                            ("AWAITING_PAYMENT", "AWAITING_PAYMENT"),
                            ("UNPAID", "UNPAID"),
                            ("PAID", "PAID"),
                        ],
                        default="NEW",
                        help_text="Current status of the order.",
                    ),
                ),
                (
                    "shipping_status",
                    models.TextField(
                        choices=[
                            ("NEW", "NEW"),
                            ("IN_PREPARATION", "IN_PREPARATION"),
                            ("WAITING_FOR_SHIPMENT", "WAITING_FOR_SHIPMENT"),
                            ("SHIPPED", "SHIPPED"),
                            ("DELIVERED", "DELIVERED"),
                            ("CLOSED", "CLOSED"),
                        ],
                        default="NEW",
                        help_text="Shipping status of the order.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Time when the order was created."
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Time when the order was last updated."
                    ),
                ),
                (
                    "total_price_with_shipping",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total price with shipping price of the order including shipping.",
                        max_digits=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Quantity of the product ordered."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Time when the order item was created.",
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Time when the order item was last updated.",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ShippingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.TextField(help_text="Type of shipping.", max_length=50),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Cost of this shipping type.",
                        max_digits=100,
                    ),
                ),
            ],
        ),
    ]
