# Generated by Django 4.2.4 on 2024-02-20 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="address",
        ),
    ]
