# Generated by Django 4.2.4 on 2024-03-03 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_remove_orderitem_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingtype",
            name="order",
        ),
    ]
