# Generated by Django 4.2.4 on 2024-04-03 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0003_remove_shippingtype_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="update_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("AWAITING_PAYMENT", "AWAITING_PAYMENT"),
                            ("PAID", "PAID"),
                            ("SHIPPED", "SHIPPED"),
                            ("DELIVERED", "DELIVERED"),
                            ("CLOSED", "CLOSED"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "total_price_with_shipping",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.address"
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipping_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.shippingtype",
                    ),
                ),
            ],
        ),
    ]
