# Generated by Django 4.2.4 on 2024-04-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_order_shipping_status_alter_order_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.TextField(
                choices=[
                    ("NEW", "NEW"),
                    ("AWAITING_PAYMENT", "AWAITING_PAYMENT"),
                    ("UNPAID", "UNPAID"),
                    ("PAID", "PAID"),
                ],
                default="NEW",
            ),
        ),
    ]
